package com.odevpedro.yugiohcollections.shared.enums;

public enum MonsterType {
    DRAGON, WARRIOR, SPELLCASTER, FIEND, FAIRY, ZOMBIE, BEAST,
    AQUA, DINOSAUR, INSECT, MACHINE, PYRO, ROCK, SEA_SERPENT,
    THUNDER, WINGED_BEAST, FISH, PLANT, PSYCHIC, REPTILE,
    CYBERSE, WYRM, DIVINE_BEAST
}