server:
  port: 8087

spring:
  application:
    name: community-service

  datasource:
    url: jdbc:postgresql://localhost:5436/communitydb
    username: community_user
    password: community_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: ${JWT_SECRET:yugioh-deck-management-super-secret-key-256bits-minimum}
  expiration-ms: 3600000 # 1 hora
