-- 1) Nova tabela de coleção do usuário
CREATE TABLE user_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    card_type VARCHAR(20) NOT NULL,       -- MONSTER | SPELL | TRAP
    card_id BIGINT NOT NULL,              -- id da carta na tabela do tipo
    quantity INT NOT NULL DEFAULT 1,
    notes VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_card UNIQUE (user_id, card_type, card_id)
);

-- (Opcional: índices para busca)
CREATE INDEX idx_user_cards_user ON user_cards(user_id);
CREATE INDEX idx_user_cards_card ON user_cards(card_type, card_id);

-- 2) (Opcional agora) Remover owner_id das tabelas de catálogo
--    Faça apenas quando tiver migrado seus serviços/consultas.
-- ALTER TABLE spell_cards  DROP COLUMN owner_id;
-- ALTER TABLE trap_cards   DROP COLUMN owner_id;
-- ALTER TABLE monster_cards DROP COLUMN owner_id;
